version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880" # HTTP/WebSocket
      - "7881:7881" # RTC over TCP
      - "7882:7882/udp" # RTC over UDP
    environment:
      - LIVEKIT_KEYS=${LIVEKIT_KEYS}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - SERVER_IP=${SERVER_IP}
    command: --keys "${LIVEKIT_KEYS}" # --node-ip ${SERVER_IP} pour l'ip publique
    restart: unless-stopped
    networks:
      - livekit-network


networks:
  livekit-network:
    driver: bridge

